### ISSUE TITLE
dbnsFullyImplicitHBFoam tutorial?

### ISSUE THREAD

**Issue by jiaqiwang969** [stefanoOliani/ICSFoam#1]
Hi, stefano,

I am really interested in this project, if is possible to add more detail of tutorial about [dbnsFullyImplicitHBFoam](https://github.com/stefanoOliani/ICSFoam/tree/master/applications/solvers/dbnsFullyImplicitHBFoam) ?

Jiaqi

**Comment by stefanoOliani** [comment]
Hi Jiaqi,

Thank you for your interest. Unfortunately, there are no tutorials that I can share for this particular solver at the moment. If you are interested, write me an email at stefano.oliani@unife.it. I can share with you the setup files (without mesh) for some test cases that I used.

Stefano
